### ISSUE TITLE
unable to compile and hot reload for development on windows 11

### ISSUE THREAD

**Issue by kendbad** [chrishham/BypassCors#2]
error
![Screenshot_6](https://user-images.githubusercontent.com/106885376/172033336-bf5903e9-d017-4ee1-971d-232eb678932e.png)

**Comment by kendbad** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/106885376/172036005-48a22746-6c01-4b82-b928-2101fb06ecde.png)

 INFO  Launching Electron...
(node:7824) [DEP0128] DeprecationWarning: Invalid 'main' field in 'D:\BypassCors\dist_electron\package.json' of 'background.js'. Please either fix that or report it to the module author
(Use `electron --trace-deprecation ...` to show where the warning was created)
Skip checkForUpdatesAndNotify because application is not packed
Uncaught (in promise) Error: Invalid header: Does not start with Cr24
    at crxToZip (webpack:///./node_modules/unzip-crx/dist/index.js?:32:15)
    at eval (webpack:///./node_modules/unzip-crx/dist/index.js?:57:32)
    at callHanler (webpack:///./node_modules/yaku/lib/yaku.js?:719:16)
    at tryCatcher (webpack:///./node_modules/yaku/lib/yaku.js?:436:32)
    at eval (webpack:///./node_modules/yaku/lib/yaku.js?:575:38)
    at flush (webpack:///./node_modules/yaku/lib/yaku.js?:478:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
>

**Comment by kendbad** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/106885376/172040436-0795b67f-42fa-4fe4-a143-f93949dd7647.png)
 INFO  Launching Electron...
(node:18488) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\kendb\BypassCors\dist_electron\package.json' of 'background.js'. Please either fix that or report it to the module author
(Use `electron --trace-deprecation ...` to show where the warning was created)
Skip checkForUpdatesAndNotify because application is not packed
(node:18488) ExtensionLoadWarning: Warnings loading extension at C:\Users\kendb\AppData\Roaming\bypass-cors\extensions\nhdogjmejiglipccpnnnanhbledajbpd:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
>

**Comment by kendbad** [comment]
I am trying to learn Electron. Level - zero.

1. I would check your node and electron versions match. Info: https://www.electronjs.org/docs/latest/tutorial/electron-timelines My version -- node 12.22.7 -- electron 11.5.0

2. I eliminated this error while learning Electron in this way: if error: "cannot find module'fs/promises' then npm uninstall electron-builder and npm i electron-builder@22.10.5

The developers claim that this bug is indeed present in node 12 and is fixed in node 14+.

**Comment by kendbad** [comment]
git clone https://github.com/chrishham/BypassCors
cd BypassCors
yarn install
yarn add  electron-devtools-installer@latest
yarn add  electron-builder@22.10.5
yarn add  electron@13.0.0

- is delete, + is edit to backgroud.js

//- protocol.registerStandardSchemes(['app'], { secure: true })
+ protocol.registerSchemesAsPrivileged([{ scheme: 'app', privileges: { secure: true } }])

//- installVueDevtools
+ import installExtension, { VUEJS_DEVTOOLS } from 'electron-devtools-installer'

//- await installVueDevtools()
+ await installExtension(VUEJS_DEVTOOLS)

add 

webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
             enableRemoteModule: true,
             nodeIntegrationInWorker: true,
        }

yarn electron:serve

done.

**Comment by chrishham** [comment]
Welldone @kendbad!

Your proposed changes were incorporated into latest commit.

Thanks a lot for taking the time to debug this.
